#!/bin/bash
# you must add the following to your ~/.netrc file
# machine ftp.claddach-kirkibost.org login tp3 password 6xx2be1qpv

# run this command in the ROOT of your svn export
# or to upload certain files use args
# eg fput application/controllers/welcome.php
HOST="ftp.claddach-kirkibost.org"
USER="tp3@claddach-kirkibost.org"
PASS="6xx2be1qpv"
LCD="~/code/uni/tp3/site"
RCD="/"
lftp -c "set ftp:list-options -a;
open ftp://$USER:$PASS@$HOST; 
lcd $LCD;
cd $RCD;
