#!/bin/bash
# you must add the following to your ~/.netrc file
# machine ftp.claddach-kirkibost.org login tp3 password 6xx2be1qpv

# you must apt-get install wput

# run this command in the ROOT of your svn export
# or to upload certain files use args
# eg fput application/controllers/welcome.php

if [ -z $1 ]; then
        svn status | grep ^M | cut -c9- | xargs -I '{}' wput -qu ftp://ftp.claddach-kirkibost.org/'{}'
else
        wput -u ftp://ftp.claddach-kirkibost.org/$1
fi

