#!/bin/bash    
HOST="ftp.claddach-kirkibost.org"
USER="tp3@claddach-kirkibost.org"
PASS="6xx2be1qpv"
LCD="~/code/uni/tp3/site"
RCD="/"
lftp -c "set ftp:list-options -a;
open ftp://$USER:$PASS@$HOST; 
lcd $LCD;
cd $RCD;
mirror --reverse \
           --verbose \
           --delete \
           --exclude-glob files/ \
           --exclude-glob application/logs/ \
           --exclude-glob incoming/ \
           --exclude-glob Final-Report/ \
           --exclude-glob wireframes/ \
           --exclude .git/ \
           --exclude .svn/"
